behaviors:
  # Blue Team - Normal Behavior
  SoccerBlue:
    trainer_type: poca
    
    hyperparameters:
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      batch_size: 2048
      buffer_size: 20480
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 1000
    summary_freq: 10000
    checkpoint_interval: 500000
    
  # Purple Team - Defensive Behavior ("Best Defense is Good Offense")
  SoccerPurple:
    trainer_type: poca
    
    hyperparameters:
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      batch_size: 2048
      buffer_size: 20480
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 1000
    summary_freq: 10000
    checkpoint_interval: 500000